Auth middleware
jabardigitalservice/servicedesk-backend pull request #3
Opened 2021-10-27 13:30 UTC by Selvyfitriani

Provide an endpoint for getting user info with custom jwt validation as middleware.

2021-10-31 23:59 UTC, ayocodingit commented on .gitignore
> +test.json
please save to env, can use base64 encryption, later decrypt to use it,

2021-11-01 01:56 UTC, tia3nt commented on .gitignore
> +test.json
ok Mas

2021-11-01 07:29 UTC, tia3nt commented
Mas Firman, Is it Ok if I keep the username and password separated from the Config file, because I think, username and password may varied in a real testcase.
Is it also possible if i parse the url so that the config file more flexible and reusable, I mean like 
define the realms name, scope name, end point first then i can define complete url separately.
because as far as I notice, token url, jwks url are basically only difference at the end point part.
I was trying a few times but no luck.

2021-11-01 08:29 UTC, ayocodingit commented
> Mas Firman, Is it Ok if I keep the username and password separated from the Config file, because I think, username and password may varied in a real testcase. Is it also possible if i parse the url so that the config file more flexible and reusable, I mean like define the realms name, scope name, end point first then i can define complete url separately. because as far as I notice, token url, jwks url are basically only difference at the end point part. I was trying a few times but no luck.

Yes, just make it as needed, but save it in the env.

2021-11-01 08:32 UTC, tia3nt commented
o Ok, thank you for your input Mas

2021-11-01 23:21 UTC, ayocodingit requested changes

2021-11-01 23:21 UTC, ayocodingit commented on package.json
> +    "@adonisjs/session": "^1.1.0",
please remove this package because unused

2021-11-01 23:21 UTC, ayocodingit commented on app/Middleware/Auth.js
> +      await next()
please remove await next(), just  method next()

2021-11-01 23:21 UTC, ayocodingit commented on test/functional/user-controller.spec.js
> +    name: 'Selvy Fitriani',
move name to env,

2021-11-02 00:21 UTC, tia3nt commented on app/Middleware/Auth.js
> +      await next()
Ok Mas

2021-11-02 02:50 UTC, ayocodingit approved these changes

2021-11-02 02:55 UTC, merged